sudo: false
language: node_js
node_js:
  - "6"
  - "8"
  - "10"
  - "node"
before_install: npm i -g greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
script:
  - npm run lint
  - npm run codecov
