sudo: false
language: node_js
node_js:
  - "6"
  - "node"
before_install: yarn global add greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
script:
  - yarn lint
  - yarn codecov
